[package]
name = "wk2-starter"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>", 
           "Zach Hauser <zachary.hauser@pomona.edu>"]

[dependencies]
nom = "^1.2.4"

[[bin]]
name = "repl"
path = "src/repl.rs"

[[bin]]
name = "stat"
path = "src/stat.rs"
